export const projects = [
	{
		id: "mcit-project-1",
		title: "MCIT Data Analysis Project 1",
		description: "Processed and analyzed highly sensitive datasets for the Ministry of Communications, ensuring data integrity and security while extracting actionable insights.",
		technologies: ["Power BI", "SQL", "Python"],
		image: "https://placehold.co/800x450/111111/ffffff?text=Confidential+MCIT+Project",
		github: "#",
		live: "#",
		featured: true,
		slug: "mcit-data-analysis-project-1",
	},
	{
		id: "mcit-project-2",
		title: "MCIT Data Analysis Project 2",
		description: "Developed interactive dashboards and performed deep data cleaning on confidential government datasets.",
		technologies: ["Power BI", "Excel", "Data Modeling"],
		image: "https://placehold.co/800x450/111111/ffffff?text=Confidential+MCIT+Project",
		github: "#",
		live: "#",
		featured: true,
		slug: "mcit-data-analysis-project-2",
	},
	{
		id: "mcit-project-3",
		title: "MCIT Data Analysis Project 3",
		description: "Designed and implemented database queries and data transformations for sensitive information to support decision-making processes.",
		technologies: ["SQL", "Power Query"],
		image: "https://placehold.co/800x450/111111/ffffff?text=Confidential+MCIT+Project",
		github: "#",
		live: "#",
		featured: true,
		slug: "mcit-data-analysis-project-3",
	},
	{
		id: "mcit-project-4",
		title: "MCIT Data Analysis Project 4",
		description: "Applied Python libraries for advanced data manipulation and visualization on classified datasets for the DEPI initiative.",
		technologies: ["Python", "Pandas", "NumPy", "Seaborn"],
		image: "https://placehold.co/800x450/111111/ffffff?text=Confidential+MCIT+Project",
		github: "#",
		live: "#",
		featured: true,
		slug: "mcit-data-analysis-project-4",
	},
];